import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

new_footer = """
<!-- Hotbar (1-5) -->
<footer class="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 pointer-events-auto">
    <div class="flex gap-2 md:gap-3" id="hotbar-grid">
        <!-- Manually adding the 5 slots since they are not generated by JS currently -->
        <div class="inventory-slot flex items-center justify-center">
            <span class="absolute top-1 left-1.5 text-[10px] font-bold text-amber-500/80">1</span>
        </div>
        <div class="inventory-slot flex items-center justify-center">
            <span class="absolute top-1 left-1.5 text-[10px] font-bold text-amber-500/80">2</span>
        </div>
        <div class="inventory-slot flex items-center justify-center">
            <span class="absolute top-1 left-1.5 text-[10px] font-bold text-amber-500/80">3</span>
        </div>
        <div class="inventory-slot flex items-center justify-center">
            <span class="absolute top-1 left-1.5 text-[10px] font-bold text-amber-500/80">4</span>
        </div>
        <div class="inventory-slot flex items-center justify-center">
            <span class="absolute top-1 left-1.5 text-[10px] font-bold text-amber-500/80">5</span>
        </div>
    </div>
</footer>
"""

html = re.sub(r'<!-- Hotbar \(1-5\) -->.*?</footer>', new_footer, html, flags=re.DOTALL)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)
